export const data=[
    {
        id:0,
        name:"Keyboard",
        price:"880.00",
        image:"https://png.pngtree.com/png-clipart/20190902/original/pngtree-keyboard--png-free-png-image_4405876.jpg",
        inStock:3,
        fastDelivery:true,
        ratings:4
    },
    {
        id:1,
        name:"Socks",
        price:"230.00",
        image:"https://freepngimg.com/thumb/gloves/52928-2-socks-download-png-image-high-quality.png",
        inStock:1,
        fastDelivery:true,
        ratings:3
    },
    {
        id:2,
        name:"Pen",
        price:"20.00",
        image:"https://pngimg.com/uploads/pen/pen_PNG7411.png",
        inStock:2,
        fastDelivery:false,
        ratings:2
    },
    {
        id:3,
        name:"Towel",
        price:"1120.00",
        image:"https://png.pngtree.com/png-clipart/20201209/original/pngtree-towel-picture-png-image_5613215.jpg",
        inStock:4,
        fastDelivery:false,
        ratings:4
    },
    {
        id:4,
        name:"Shirt",
        price:"800.00",
        image:"https://png.pngtree.com/png-clipart/20201209/original/pngtree-cotton-short-sleeve-t-shirt-png-image_5625083.jpg",
        inStock:0,
        fastDelivery:false,
        ratings:5
    },
    {
        id:5,
        name:"Bucket",
        price:620.00,
        image:"https://png.pngtree.com/png-clipart/20190920/original/pngtree-pink-bucket-png-image_4652748.jpg",
        inStock:0,
        fastDelivery:false,
        ratings:2
    },
    {
        id:6,
        name:"Hat",
        price:700.00,
        image:"https://image.shutterstock.com/image-photo/white-bucket-hat-isolated-on-260nw-2126718404.jpg",
        inStock:4,
        fastDelivery:true,
        ratings:1
    },
    {
        id:7,
        name:"Shoes",
        price:920.00,
        image:"https://png.pngtree.com/png-clipart/20201209/original/pngtree-travel-shoes-casual-shoes-scene-map-png-image_5617048.jpg",
        inStock:2,
        fastDelivery:true,
        ratings:5
    },
    {
        id:8,
        name:"Water Bottle",
        price:990.00,
        image:"https://png.pngtree.com/png-clipart/20190902/original/pngtree-two-bottles-of-water-bottles-are-taken-in-real-time-png-image_4406920.jpg",
        inStock:2,
        fastDelivery:true,
        ratings:5
    },
    {
        id:9,
        name:"NoteBook",
        price:420.00,
        image:"https://png.pngtree.com/png-clipart/20210516/original/pngtree-notebook-business-writing-books-png-image_6281400.jpg",
        inStock:2,
        fastDelivery:false,
        ratings:2
    },
    {
        id:10,
        name:"Lock",
        price:220.00,
        image:"https://png.pngtree.com/png-clipart/20190916/original/pngtree-golden-lock-png-image_4587951.jpg",
        inStock:2,
        fastDelivery:true,
        ratings:3
    },
    {
        id:11,
        name:"Rope",
        price:180.00,
        image:"https://png.pngtree.com/png-clipart/20210311/original/pngtree-knotted-binding-tool-hemp-rope-png-image_5983148.jpg",
        inStock:3,
        fastDelivery:true,
        ratings:1
    },
    {
        id:12,
        name:"Headphone",
        price:850.00,
        image:"https://png.pngtree.com/png-clipart/20201209/original/pngtree-headphones-png-image_5643350.jpg",
        inStock:4,
        fastDelivery:true,
        ratings:5
    },
    {
        id:13,
        name:"bowl",
        price:320.00,
        image:"https://png.pngtree.com/png-clipart/20190904/original/pngtree-bowl--png-free-png-image_4482137.jpg",
        inStock:2,
        fastDelivery:true,
        ratings:3
    },
    
];